### ISSUE TITLE
Issue building with cmake 3.17 and Visual Studio 2019

### ISSUE THREAD

**Issue by jackjansen** [Aschratt/DotNetWithCMake#1] opened 2020-11-25 20:25 UTC
I'm trying to learn about creating a c# assembly with cmake, and this project seems to be a good starting point.
Unfortunately it doesn't seem to work with what I have installed on my system (cmake 3.17, Visual Studio 2019), or using my normal cmake sequence of commands.

I do:

```
$ git clone https://github.com/Aschratt/DotNetWithCMake.git
$ cd DotNetWithCMake/
$ mkdir build
$ cd build
$ cmake .. -G "Visual Studio 16 2019" -A x64
 ```

But cmake cannot find various files it needs:

```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Warning at CommonLib/CMakeLists.txt:2 (PROJECT):
  the following parameters must be specified after LANGUAGES keyword:
  1.0.0.0.


CMake Error: Could not find cmake module file: CMakeDetermine1.0.0.0Compiler.cmake
CMake Error: Could not find cmake module file: C:/Users/VRTogether/src/DotNetWithCMake/CMakeFiles/3.17.0/CMake1.0.0.0Compiler.cmake
CMake Error at CommonLib/CMakeLists.txt:2 (PROJECT):
  No CMAKE_1.0.0.0_COMPILER could be found.



CMake Error: Could not find cmake module file: CMake1.0.0.0Information.cmake
-- Configuring incomplete, errors occurred!
See also "C:/Users/VRTogether/src/DotNetWithCMake/CMakeFiles/CMakeOutput.log".
See also "C:/Users/VRTogether/src/DotNetWithCMake/CMakeFiles/CMakeError.log".
```
Manually running `../CMakeFiles/3.17.0/CompilerIdCSharp/CompilerIdCSharp.exe` suggests that maybe VS2019 is too new, but I'm not sure:

```
$ ../CMakeFiles/3.17.0/CompilerIdCSharp/CompilerIdCSharp.exe
INFO:compiler[Microsoft unknown]
INFO:platform[Windows]
INFO:arch[x64]
INFO:compiler_version[9999]
$ 
```

**Comment by crud89** [comment] 2020-11-25 21:26
I've looked into the issue and could reproduce it with CMake 3.18.1. The original template has been created with CMake 3.14 and VS 2019. I don't know why it worked in the first place, but making the `VERSION` attribute for the projects explicit resolves the issue for me.

Note that there were some other minor issues (mostly wrong naming, since I've ported this template out of an existing project I've been working on). You can pull the last two commits and see if it works for you. Let me know if you have any further problems! 🙃

**Comment by crud89** [comment] 2020-11-30 09:31
Closing for now. Let me know if you still have trouble! 🙂

**Closed as completed by crud89** 2020-11-30 09:31 UTC

**Comment by jackjansen** [comment] 2020-11-30 20:48
Thanks, that fixed it!
